### ISSUE TITLE
Support flexible column names

### ISSUE THREAD

**Issue by C0kkie** [Davepar/gcalendarsync#14]
I get this error, my sheet looks like:

![c0kkie_21-12-2016_19-51-39](https://cloud.githubusercontent.com/assets/20169938/21402035/0473d6cc-c7b7-11e6-8065-f43ed3261f50.png)

and my edited script:

![c0kkie_21-12-2016_19-52-10](https://cloud.githubusercontent.com/assets/20169938/21402051/152f80ce-c7b7-11e6-840b-7dbef367d75f.png)

**Comment by Davepar** [comment]
Guten Tag

I can only speak a little Deutsch, so I'll switch to English. When I wrote this script, I didn't think about supporting other languages. The logic of the script depends on the fields being called "Title", "Description", etc. I'll think about how I can modify it to be more flexible.

**Comment by C0kkie** [comment]
Okay would be nice

**Comment by Davepar** [comment]
I made some changes to the script, which should allow you to set the column names to whatever you like. Please try it out and let me know if you run into any problems.
