### ISSUE TITLE
Change default Start Time?

### ISSUE THREAD

**Issue by jingyang81** [Davepar/gcalendarsync#18]
Hi Dave, excellent script, it's very useful. I'm using it to block my Airbnb calendar. However, if I put start date (for example January 1st) the Date/time format make it January 1, 12am. Can I modify the script to make it always start at 2pm?

**Comment by Davepar** [comment]
I think this is a limitation of calendar. It assumes an all day event starts at midnight. I think you'd have to specify the start date with a time, like Jan 1, 2pm.
