### ISSUE TITLE
Not working after the first fow

### ISSUE THREAD

**Issue by DoveCon** [Davepar/gcalendarsync#24]
Hi I have made a copy of the file as per the instructions and have managed to successfully create an even however when I try to create a second even I get "TypeError: Cannot call method "split" of undefined." error message. 

Also I have noticed that the time the events are created are not the same as the are meant to. I have set the region on my spread sheet to the same as my calendar but still an 8am event gets created at 11pm.

**Comment by Davepar** [comment]
Looks like a bug introduced by the new event guest logic. I'll have a fix pushed in a few minutes.

**Comment by Davepar** [comment]
I just noticed the second issue. Are you sure the time zones are set the same for the calendar and the spreadsheet? The calendar time zone is set in "Calendar Settings" accessible from the little drop down menu next to the calendar title in the list along the left side.

**Comment by DoveCon** [comment]
Hi Dave

I had a second play with the file and looks like it is fine. Maybe as
initially I had it set in two different time zone and opened more then once
it didn't accept the time zone change. Now the time issue seems to be
working fine, Thanks for the quick response.

*_________________________________*


*Martin Vallo*
Content Editor

Office:  +39 051 0953333
Skype: vallo.m
Web:    https://corporate.doveconviene.it/

*Notice. The information contained in this message is intended only for use
of the individuals named above. The message may contain confidential,
proprietary or legally privileged information. If you are not the intended
recipient of this message, you must not use, disseminate or copy it in any
form or take any action in reliance of it. If you have received this
message in error, please delete it and notify the sender immediately. This
e-mail address is not a private address and, therefore, its use is
regulated.*
