### ISSUE TITLE
Change start point & omit cal -> spreadsheet

### ISSUE THREAD

**Issue by ztucker** [Davepar/gcalendarsync#33]
Hello,

I am new to programming so apologies in advance for the stupid questions. 

I have hundreds of entries that go back a few years, and I want to sync only the events from the current date forward. Is there any way to add that into the script so it doesn't start all the way back in 2016 or even for events that happened last week?

Also - I am only planning to use the script to sync spreadsheet to calendar. I do not need to sync from cal to SS. Are there parts of the script I can safely omit to declutter it without messing up the function?

Thanks so much!

**Comment by Davepar** [comment]
I'll work on an update to make it easier to specify a particular start/end date, including the current date. Hopefully this weekend.

It would be fairly easy to remove the "from calendar" option from the menu. Just take out the first entry in the "menuEntries" array around line 46. Just be aware that you'll need to do that every time you update the script if you grab a new version in the future.

Dave

**Comment by Davepar** [comment]
I just made a change that makes it easier to ignore any events in the past. Near the top of the script change the beginDate line to this: `var beginDate = new Date()`.

**Comment by MikeCHughes** [comment]
Hi Dave,

First thanks for this script, it is brilliant and simple to use. However, I have tried to add a column and can't get it to work. I should point out that I am not good with JavaScript.

I added a column called "Stand" and in the "var titleRowMap" section added the line "'stand': 'Stand'," Then I added "'stand': calEvent.getStand()," in the "function convertCalEvent(calEvent)" along with similar (what I believe to be relevant) references in the "var convertedCalEvent" and "function updateEvent(calEvent, sheetEvent)" sections. But when I run the "Calendar Sync" I get the error message "TypeError: Cannot find function getStand in object CalendarEvent."

I have tried redoing the references a couple of times in case I got something wrong with the syntax plus I even tried moving the statements about in the lists just in case, but it makes no difference.

Any idea what I am doing wrong please - a loop that needs amending perhaps?
