### ISSUE TITLE
Sync new calendar event to spreadsheet automatically

### ISSUE THREAD

**Issue by tisseuil** [Davepar/gcalendarsync#38]
Hi !

Thanks a lot for your very very nice script. 

I am looking for a way to sync new calendar events to the spreadsheet automatically using the triggers features. For instance, I have tried to configure the SyncFromCalendar function to run every minutes. However, when I am adding a new event in calendar, it is not added to the spreadsheet after a couple of minutes... 

Any ideas how I could solve this issue ?

Kind regards

Clement

**Comment by tisseuil** [comment]
Hi again !

I have found the solution... there was a small bug in my calendar settings ! Your function works perfectly with the trigger options !

Thanks

Clem

**Comment by jandrostory81** [comment]
What was the bug in your calendar settings?

**Comment by brianfigg** [comment]
[image: Screen Shot 2019-08-04 at 6.24.46 PM.png]
