### ISSUE TITLE
Events deleted from spreadsheet whether new or old

### ISSUE THREAD

**Issue by Meamsosmart** [Davepar/gcalendarsync#4]
Hi Dave, Great script! Mostly because I am not a programmer and it would take me forever to figure it out.  However, I hope to learn soon.  I opened up your test calendar and it wrote all of the events to my calendar wonderfully.  The problem is, I was left with a blank spreadsheet afterwards!  I easily then synched from the calendar to the spreadsheet to repopulate it, but I would rather not have that happen. As far as I can tell, you do not intend that to happen with this script.  I can't see anywhere in the script where it would delete an entry once it is written to the calendar.  I hope this has not already been addressed in the comments, but I think previous issues were related to just deleted functions, not deleting all the data. Thanks, Victor

**Comment by Davepar** [comment]
I just added a fix to the script to address this. I was trying to fix a problem with preserving formulas reported in issue #3, but ended up causing data to be deleted. Let me know if this doesn't fix the problem.

**Comment by Meamsosmart** [comment]
Thanks so much Dave!  I figured it was an unintended by-product of your other fix.  It fixed the problem.  I was able to test it soon after, it just took me a  while to thank you!


Victor Sprenger, DVM, MSc Eng, BSc Eng 




 


Date: Fri, 26 Feb 2016 09:30:35 -0800
