### ISSUE TITLE
could you add support for multiple CALs with IDs ? please :)

### ISSUE THREAD

**Issue by yetson0** [Davepar/gcalendarsync#53]
if the script could work with multiple calendars (IDs) it would be excellent !
just another column for calendar ID ...

is it lot of coding ?

yetson

ps. unfortunately I am a .gs newbie so tweaking in your script will not work for me :(
pps. thank you so far for this script.

**Comment by jandrostory81** [comment]
Hi @Davepar! This script is fantastic! I have create an app in appsheet that looks great but I really needed this.  How can we update this to add a "calendar" column that pulls from the calendar name?  I have 6 Calendars I am trying to combine into one on my app using a spreadsheet.  Is there any way this is possible?  This is the last step to creating my app.  Any help with how to edit this code to allow this would be amazing!!!!! Thank you

**Comment by Davepar** [comment]
This is a fair amount of work, but 3 people have asked for it so far. I'll consider doing this in the future.

**Comment by laraklee** [comment]
This suggestion sounds really useful. I'm a .gs newbie, too... so maybe this isn't possible - but maybe passing the calendarID as an argument when calling the function? Then, if one cell on a given sheet (would it work to put it in the A row?) had the calendar ID in it, the function could grab that from the active sheet as the argument? That would also allow the feature - having different sheet tabs sync to different calendars. Again, apologies if as a newbie, this idea is ridiculous.

**Comment by Davepar** [comment]
This is now implemented.
