### ISSUE TITLE
Whole Day Events

### ISSUE THREAD

**Issue by themacmarketer** [Davepar/gcalendarsync#59]
Hello,

Would it be possible for this script to handle whole day events, even when the start and end dates are entered?

Currently, it seems to create whole day events only when the end date is blank.

I'd like it to create only whole day events, even when an end date is input.

Any advice on how to modify the code would be much appreciated.

Thanks,
Ivan

**Comment by Davepar** [comment]
I'm working on a complete rewrite of the script right now. I changed the logic to allow multi-day, all-day events. In other words, you'll be able to specify a start and end date for all day events. I'll hopefully have it published in the next week or two.

**Comment by Davepar** [comment]
This is fixed now.
