### ISSUE TITLE
Event Color with string instead of number

### ISSUE THREAD

**Issue by evangjes** [Davepar/gcalendarsync#68]
Hi Dave,

I've been using the GSuite Marketplace edition and noted color is set with a string instead of a number. Is there a way to implement this with the Apps Script? 

Let me know what you think.

Evan

**Comment by Davepar** [comment]
It should be fairly straightforward to map color strings to the indices. Unfortunately I don't really have time to support both versions of the add-on. I've been putting all of my efforts into the GSuite Marketplace version. Sorry.
