### ISSUE TITLE
ENDTIME wrong sync with one day extra.

### ISSUE THREAD

**Issue by jbcastella** [Davepar/gcalendarsync#70]
I'm experiencing problems with the endtime sync. The Addon syncs the ENDTIME incorrectly.

Attached images:
![image](https://user-images.githubusercontent.com/42608082/90578150-ddd74880-e1c2-11ea-959a-bd266b55a7c0.png)

![image](https://user-images.githubusercontent.com/42608082/90578201-fe070780-e1c2-11ea-8ace-e005fe0c91ab.png)

Anyway, thanks for the add-on! Great job!

**Comment by Davepar** [comment]
Thanks for the bug report. This was just reported by another person as well. I think it's related to time zones. The add-on seems to run in the US/Pacific time zone, which causes problems anywhere else. I'll try to take a look at the issue tomorrow.

**Comment by crysman** [comment]
related issue: https://github.com/Davepar/gcalendarsync/issues/72

**Comment by Davepar** [comment]
This should be fixed now. Re-open if you still have problems.
