### ISSUE TITLE
Exception: Action not allowed error on shared google sheet.

### ISSUE THREAD

**Issue by jacksingh99** [Davepar/gcalendarsync#82]
Hello Dave,
I am able to run this add-on on my sheet successfully but the person I am sharing the Google sheet gets "Action not allowed" error  when they try to run "Update to Calendar" part of the add on. We only update to calendar. We both were able to use the older version but decided to use the add on instead.

**Comment by jacksingh99** [comment]
Hello Dave,
The error was being produced because the person I was sharing the calendar with did not have permission to make changes to events. I gave permission to allow to make changes to events and now it works.

**Comment by Davepar** [comment]
Glad you got it sorted out!
